### PR TITLE
Bubble Sort Algorithm

### LINKED ISSUE #4: Bubble Sort Algorithm
Write an implementation of bubble sort algorithm on an integer array with proper explanation through comments.

### PR DESCRIPTION
**Pull request by JoaoDanielRufino**
Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>

Closes #4

### CODE REVIEW

**Comment by prafulla-k-roy** [comment]
I already received bubble sort in C++. Can you perform the same in Java? I will accept it in Java.

**Review by prafulla-k-roy — CHANGES_REQUESTED** [review]
Please perform the same algorithm in Java or Python, as I have already received the algorithm in C++. I appreciate your contribution and you explanation is well up to the mark. Just change it to another programming language if possible.

**Comment by JoaoDanielRufino** [comment]
> Please perform the same algorithm in Java or Python, as I have already received the algorithm in C++. I appreciate your contribution and you explanation is well up to the mark. Just change it to another programming language if possible.

Can I do it in Golang ?

**Comment by JoaoDanielRufino** [comment]
@prafulla-k-roy , I've added the Java implementation

**Pull request merged**
